#
# Autogenerated by Thrift Compiler (0.9.3)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

require 'thrift'

class PageContentItem
  include ::Thrift::Struct, ::Thrift::Struct_Union
  RAW = 1
  FULLTEXT = 2
  ARTICLETEXT = 3
  DOM = 4

  FIELDS = {
    RAW => {:type => ::Thrift::Types::STRING, :name => 'raw', :binary => true, :optional => true},
    FULLTEXT => {:type => ::Thrift::Types::STRING, :name => 'fullText', :optional => true},
    ARTICLETEXT => {:type => ::Thrift::Types::STRING, :name => 'articleText', :optional => true},
    DOM => {:type => ::Thrift::Types::STRING, :name => 'dom', :optional => true}
  }

  def struct_fields; FIELDS; end

  def validate
  end

  ::Thrift::Struct.generate_accessors self
end

class Context
  include ::Thrift::Struct, ::Thrift::Struct_Union
  LEFT = 1
  RIGHT = 2
  MIDDLE = 3

  FIELDS = {
    LEFT => {:type => ::Thrift::Types::STRING, :name => 'left'},
    RIGHT => {:type => ::Thrift::Types::STRING, :name => 'right'},
    MIDDLE => {:type => ::Thrift::Types::STRING, :name => 'middle'}
  }

  def struct_fields; FIELDS; end

  def validate
  end

  ::Thrift::Struct.generate_accessors self
end

class Mention
  include ::Thrift::Struct, ::Thrift::Struct_Union
  WIKI_URL = 1
  ANCHOR_TEXT = 2
  RAW_TEXT_OFFSET = 3
  CONTEXT = 4
  FREEBASE_ID = 5

  FIELDS = {
    WIKI_URL => {:type => ::Thrift::Types::STRING, :name => 'wiki_url'},
    ANCHOR_TEXT => {:type => ::Thrift::Types::STRING, :name => 'anchor_text'},
    RAW_TEXT_OFFSET => {:type => ::Thrift::Types::I32, :name => 'raw_text_offset'},
    CONTEXT => {:type => ::Thrift::Types::STRUCT, :name => 'context', :class => ::Context, :optional => true},
    FREEBASE_ID => {:type => ::Thrift::Types::STRING, :name => 'freebase_id', :optional => true}
  }

  def struct_fields; FIELDS; end

  def validate
  end

  ::Thrift::Struct.generate_accessors self
end

class RareWord
  include ::Thrift::Struct, ::Thrift::Struct_Union
  WORD = 1
  OFFSET = 2

  FIELDS = {
    WORD => {:type => ::Thrift::Types::STRING, :name => 'word'},
    OFFSET => {:type => ::Thrift::Types::I32, :name => 'offset'}
  }

  def struct_fields; FIELDS; end

  def validate
  end

  ::Thrift::Struct.generate_accessors self
end

class WikiLinkItem
  include ::Thrift::Struct, ::Thrift::Struct_Union
  DOC_ID = 1
  URL = 2
  CONTENT = 3
  RARE_WORDS = 4
  MENTIONS = 5

  FIELDS = {
    DOC_ID => {:type => ::Thrift::Types::I32, :name => 'doc_id'},
    URL => {:type => ::Thrift::Types::STRING, :name => 'url'},
    CONTENT => {:type => ::Thrift::Types::STRUCT, :name => 'content', :class => ::PageContentItem},
    RARE_WORDS => {:type => ::Thrift::Types::LIST, :name => 'rare_words', :element => {:type => ::Thrift::Types::STRUCT, :class => ::RareWord}},
    MENTIONS => {:type => ::Thrift::Types::LIST, :name => 'mentions', :element => {:type => ::Thrift::Types::STRUCT, :class => ::Mention}}
  }

  def struct_fields; FIELDS; end

  def validate
  end

  ::Thrift::Struct.generate_accessors self
end

